export const HEADERS:string[]=[
      'No.',
      'FECHA DE PUBLICACIÓN',
      'TIPO DE PROCESO',
      'ABREVIATURA DE PROCESO',
      'NÚMERO DE PROCESO',
      'CÓDIGO DE PROCESO',
      'DETALLE',
      'ESTADO',
      'OFICIO',
      'CONTRATISTA',
      'AÑO',
      'VALOR CONTRATADO',
      'DEPARTAMENTO',
]