/*
*Espacio de tablas eeasa
*/
CREATE TABLESPACE EEASA DATAFILE 'eeasa.dbf' SIZE 10G;

/*
*Usuario liquidaciones
*/
CREATE USER LIQUIDACIONES IDENTIFIED BY System2013;
GRANT CONNECT TO LIQUIDACIONES;
GRANT UNLIMITED TABLESPACE TO LIQUIDACIONES;
GRANT CREATE VIEW TO LIQUIDACIONES;
GRANT RESOURCE TO LIQUIDACIONES;

/*
*Usuario SGC
*/
CREATE USER SGC IDENTIFIED BY System2013;
GRANT CONNECT TO SGC;
GRANT UNLIMITED TABLESPACE TO SGC;
GRANT CREATE VIEW TO SGC;
GRANT RESOURCE TO SGC;

/*
*Usuario CONTRATISTA
*/
CREATE USER CONTRATISTA IDENTIFIED BY intranet2019_;
GRANT CONNECT TO CONTRATISTA;
GRANT UNLIMITED TABLESPACE TO CONTRATISTA;
GRANT CREATE VIEW TO CONTRATISTA;
GRANT RESOURCE TO CONTRATISTA;